// <auto-generated />
namespace MPI_Report.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddInspectionTrackPlatform : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInspectionTrackPlatform));
        
        string IMigrationMetadata.Id
        {
            get { return "202609300100000_AddInspectionTrackPlatform"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
